site_name: GOS Analyzer Documentation

theme:
  name: material

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            members: true
            show_if_no_docstring: false
            filters:
              - "!^_"

nav:
  - Home: index.md
  - Tutorials:
      - Getting Started: tutorials/getting-started.md
  - API:
      - Extractor: api/extractor.md
      - Gliner: api/gliner.md
      - Account Extractor: api/account_extractor.md
