site_name: GOS Analyzer Documentation

theme:
  name: material

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            members: true
            show_if_no_docstring: false
            filters:
              - "!^_"

nav:
  - Home: index.md
  - Tutorials:
      - Getting Started: tutorials/getting_started.md
  - API:
    - Financial:
      - Amount Extractor: api/financial/amount_extractor.md
      - Extractor: api/financial/extractor.md
    - Linker:
      - Backend Processor: api/linker/backend_processor.md
    - NER:
      - Gliner Service: api/ner/gliner_service.md
      - Account IFSC Extractor: api/ner/account_ifsc_extractor.md
      - IFSC Mapper: api/ner/ifsc_mapper.md
      - Regex Extractor: api/ner/regex-extractor.md
      - Formatter: api/ner/formatter.md
    - SQA:
      - Retreiver: api/sqa/retriever.md
      - Scorer: api/sqa/scorer.md
      - Segmenter: api/sqa/segmenter.md
      - UI: api/sqa/ui.md
      - Utils: api/sqa/utils.md
    - Main:
      - api/main.md